name: Test system_metrics_collector
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros@0.0.11
    - uses: ros-tooling/action-ros-ci@0d723c705fa05402c6399a2ad33a324a0119ff95
      with:
        package-name: system_metrics_collector
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      # Prevent being rate limited by only reporting coverage from the Ubuntu
      # build.
      if: matrix.os == 'ubuntu-18.04'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros2_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros2_ws/log

  build_and_test_asan:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros2@0.0.6
    - uses: ros-tooling/action-ros2-ci@0.0.10
      with:
        colcon-mixin-name: asan
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        package-name: system_metrics_collector
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}-asan
        path: ros2_ws/log
