name: Test system_metrics_collector
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros2@0.0.11
    - uses: ros-tooling/action-ros2-ci@0.0.11
      with:
        package-name: system_metrics_collector
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    # GitHub action support is currently broken on the original upstream
    # repository. This fork fixes support until the problem is fixed upstream.
    - uses: ros-tooling/codecov-action@master
      if: matrix.os == 'ubuntu-18.04'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ros2_ws/lcov/total_coverage.info
        # codecov-action is a Docker action, and as such can only run on Linux.
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros2_ws/log

  build_and_test_asan:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros2@0.0.11
    - uses: ros-tooling/action-ros2-ci@0.0.11
      with:
        colcon-mixin-name: asan
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        package-name: system_metrics_collector
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}-asan
        path: ros2_ws/log

  build_and_test_clang:
    runs-on: ubuntu-18.04
    steps:
    - uses: ros-tooling/setup-ros2@0.0.11
    - uses: ros-tooling/action-ros2-ci@0.0.11
      with:
        colcon-mixin-name: clang-libcxx
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        package-name: system_metrics_collector
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}-clang-libcxx
        path: ros2_ws/log
