name: Test system_metrics_collector
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest]
    steps:
    - uses: ros-tooling/setup-ros2@0.0.6
    - uses: ros-tooling/action-ros2-ci@tmoulard/fix-osx2
      with:
        package-name: system_metrics_collector
    # GitHub action support is currently broken on the original upstream
    # repository. This fork fixes support until the problem is fixed upstream.
    - uses: ros-tooling/codecov-action@master
      if: matrix.os == 'ubuntu-18.04'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ros2_ws/lcov/total_coverage.info
        # codecov-action is a Docker action, and as such can only run on Linux.
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros2_ws/log
